name: test script
on:
  pull_request:
    types: [opened, reopened, edited]
    branches: develop

jobs:
  test_script_syntax_and_style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: test script
        id: test_script
        run: |
          bash -n script.sh

