name: test script
on:
  pull_request:
    types: [opened]

jobs:
  test_script_syntax_and_style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: test script
        run: |
          bash -n script.sh
