name: test script
on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  test_script_syntax_and_style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: test script
        id: test_script
        run: |
          result=$(bash -n script.sh)
          ::set-output name=result::${result}
      - name: post result to PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ${{ steps.test_script.outputs.result }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
